<?php

class MixtureDevTableSeeder extends Seeder
{
	public function run()
	{
		DB::table('mixture_dev')->delete();
		$mixture_dev = [
			['id' => '1', 'purpose' => 'autoall', 'name' => 'MEGAGROUP ALL', 'desc' => 'AutoGenerate ALL dev', 'trigger_column_count' => '139'],
			['id' => '10', 'purpose' => 'devgroup', 'name' => 'GROUP Makita', 'desc' => NULL, 'trigger_column_count' => '3'],
			['id' => '12', 'purpose' => 'devgroup', 'name' => 'GROUP Bow', 'desc' => NULL, 'trigger_column_count' => '14'],
			['id' => '13', 'purpose' => 'devgroup', 'name' => 'GROUP Madalbal', 'desc' => NULL, 'trigger_column_count' => '11'],
			['id' => '14', 'purpose' => 'devgroup', 'name' => 'GROUP Garland', 'desc' => NULL, 'trigger_column_count' => '21'],
			['id' => '15', 'purpose' => 'devgroup', 'name' => 'GROUP Proma', 'desc' => NULL, 'trigger_column_count' => '3'],
			['id' => '16', 'purpose' => 'devgroup', 'name' => 'GROUP V-Garden', 'desc' => NULL, 'trigger_column_count' => '0'],
			['id' => '17', 'purpose' => 'devgroup', 'name' => 'GROUP Igm', 'desc' => NULL, 'trigger_column_count' => '7'],
			['id' => '18', 'purpose' => 'autosimple', 'name' => 'ONLY Makita', 'desc' => 'AutoGenerate only dev: Makita', 'trigger_column_count' => '1'],
			['id' => '19', 'purpose' => 'autosimple', 'name' => 'ONLY Maktec', 'desc' => 'AutoGenerate only dev: Maktec', 'trigger_column_count' => '1'],
			['id' => '20', 'purpose' => 'autosimple', 'name' => 'ONLY Narex', 'desc' => 'AutoGenerate only dev: Narex', 'trigger_column_count' => '1'],
			['id' => '21', 'purpose' => 'autosimple', 'name' => 'ONLY Protool', 'desc' => 'AutoGenerate only dev: Protool', 'trigger_column_count' => '1'],
			['id' => '22', 'purpose' => 'autosimple', 'name' => 'ONLY Metabo', 'desc' => 'AutoGenerate only dev: Metabo', 'trigger_column_count' => '1'],
			['id' => '23', 'purpose' => 'autosimple', 'name' => 'ONLY Dolmar', 'desc' => 'AutoGenerate only dev: Dolmar', 'trigger_column_count' => '1'],
			['id' => '24', 'purpose' => 'autosimple', 'name' => 'ONLY Proma', 'desc' => 'AutoGenerate only dev: Proma', 'trigger_column_count' => '1'],
			['id' => '25', 'purpose' => 'autosimple', 'name' => 'ONLY Ferm', 'desc' => 'AutoGenerate only dev: Ferm', 'trigger_column_count' => '1'],
			['id' => '26', 'purpose' => 'autosimple', 'name' => 'ONLY Dewalt', 'desc' => 'AutoGenerate only dev: Dewalt', 'trigger_column_count' => '1'],
			['id' => '27', 'purpose' => 'autosimple', 'name' => 'ONLY Narex Bystřice', 'desc' => 'AutoGenerate only dev: Narex Bystřice', 'trigger_column_count' => '1'],
			['id' => '28', 'purpose' => 'autosimple', 'name' => 'ONLY Flexovit', 'desc' => 'AutoGenerate only dev: Flexovit', 'trigger_column_count' => '1'],
			['id' => '29', 'purpose' => 'autosimple', 'name' => 'ONLY ABAC', 'desc' => 'AutoGenerate only dev: ABAC', 'trigger_column_count' => '1'],
			['id' => '30', 'purpose' => 'autosimple', 'name' => 'ONLY Telwin', 'desc' => 'AutoGenerate only dev: Telwin', 'trigger_column_count' => '1'],
			['id' => '31', 'purpose' => 'autosimple', 'name' => 'ONLY Oregon', 'desc' => 'AutoGenerate only dev: Oregon', 'trigger_column_count' => '1'],
			['id' => '32', 'purpose' => 'autosimple', 'name' => 'ONLY Festool', 'desc' => 'AutoGenerate only dev: Festool', 'trigger_column_count' => '1'],
			['id' => '33', 'purpose' => 'autosimple', 'name' => 'ONLY Knipex', 'desc' => 'AutoGenerate only dev: Knipex', 'trigger_column_count' => '1'],
			['id' => '34', 'purpose' => 'autosimple', 'name' => 'ONLY Stanley', 'desc' => 'AutoGenerate only dev: Stanley', 'trigger_column_count' => '1'],
			['id' => '35', 'purpose' => 'autosimple', 'name' => 'ONLY Elko Nový Knín', 'desc' => 'AutoGenerate only dev: Elko Nový Knín', 'trigger_column_count' => '1'],
			['id' => '36', 'purpose' => 'autosimple', 'name' => 'ONLY Fein', 'desc' => 'AutoGenerate only dev: Fein', 'trigger_column_count' => '1'],
			['id' => '37', 'purpose' => 'autosimple', 'name' => 'ONLY Hitachi', 'desc' => 'AutoGenerate only dev: Hitachi', 'trigger_column_count' => '1'],
			['id' => '38', 'purpose' => 'autosimple', 'name' => 'ONLY Lumag', 'desc' => 'AutoGenerate only dev: Lumag', 'trigger_column_count' => '1'],
			['id' => '39', 'purpose' => 'autosimple', 'name' => 'ONLY Oren', 'desc' => 'AutoGenerate only dev: Oren', 'trigger_column_count' => '1'],
			['id' => '40', 'purpose' => 'autosimple', 'name' => 'ONLY Master', 'desc' => 'AutoGenerate only dev: Master', 'trigger_column_count' => '1'],
			['id' => '41', 'purpose' => 'autosimple', 'name' => 'ONLY Wiha', 'desc' => 'AutoGenerate only dev: Wiha', 'trigger_column_count' => '1'],
			['id' => '42', 'purpose' => 'autosimple', 'name' => 'ONLY Fiskars', 'desc' => 'AutoGenerate only dev: Fiskars', 'trigger_column_count' => '1'],
			['id' => '43', 'purpose' => 'autosimple', 'name' => 'ONLY Sankyo', 'desc' => 'AutoGenerate only dev: Sankyo', 'trigger_column_count' => '1'],
			['id' => '44', 'purpose' => 'autosimple', 'name' => 'ONLY Worx', 'desc' => 'AutoGenerate only dev: Worx', 'trigger_column_count' => '1'],
			['id' => '45', 'purpose' => 'autosimple', 'name' => 'ONLY Proteco', 'desc' => 'AutoGenerate only dev: Proteco', 'trigger_column_count' => '1'],
			['id' => '46', 'purpose' => 'autosimple', 'name' => 'ONLY Al-ko', 'desc' => 'AutoGenerate only dev: Al-ko', 'trigger_column_count' => '1'],
			['id' => '47', 'purpose' => 'autosimple', 'name' => 'ONLY WAY', 'desc' => 'AutoGenerate only dev: WAY', 'trigger_column_count' => '1'],
			['id' => '48', 'purpose' => 'autosimple', 'name' => 'ONLY Lescha', 'desc' => 'AutoGenerate only dev: Lescha', 'trigger_column_count' => '1'],
			['id' => '49', 'purpose' => 'autosimple', 'name' => 'ONLY Bow', 'desc' => 'AutoGenerate only dev: Bow', 'trigger_column_count' => '1'],
			['id' => '50', 'purpose' => 'autosimple', 'name' => 'ONLY Aircraft', 'desc' => 'AutoGenerate only dev: Aircraft', 'trigger_column_count' => '1'],
			['id' => '51', 'purpose' => 'autosimple', 'name' => 'ONLY Holzstar', 'desc' => 'AutoGenerate only dev: Holzstar', 'trigger_column_count' => '1'],
			['id' => '52', 'purpose' => 'autosimple', 'name' => 'ONLY Holzkraft', 'desc' => 'AutoGenerate only dev: Holzkraft', 'trigger_column_count' => '1'],
			['id' => '53', 'purpose' => 'autosimple', 'name' => 'ONLY Numco', 'desc' => 'AutoGenerate only dev: Numco', 'trigger_column_count' => '1'],
			['id' => '54', 'purpose' => 'autosimple', 'name' => 'ONLY Metallkraft', 'desc' => 'AutoGenerate only dev: Metallkraft', 'trigger_column_count' => '1'],
			['id' => '55', 'purpose' => 'autosimple', 'name' => 'ONLY Optimum', 'desc' => 'AutoGenerate only dev: Optimum', 'trigger_column_count' => '1'],
			['id' => '56', 'purpose' => 'autosimple', 'name' => 'ONLY Quantum', 'desc' => 'AutoGenerate only dev: Quantum', 'trigger_column_count' => '1'],
			['id' => '57', 'purpose' => 'autosimple', 'name' => 'ONLY Schweißkraft', 'desc' => 'AutoGenerate only dev: Schweißkraft', 'trigger_column_count' => '1'],
			['id' => '58', 'purpose' => 'autosimple', 'name' => 'ONLY Unicraft', 'desc' => 'AutoGenerate only dev: Unicraft', 'trigger_column_count' => '1'],
			['id' => '59', 'purpose' => 'autosimple', 'name' => 'ONLY Sieg', 'desc' => 'AutoGenerate only dev: Sieg', 'trigger_column_count' => '1'],
			['id' => '60', 'purpose' => 'autosimple', 'name' => 'ONLY RÖHM', 'desc' => 'AutoGenerate only dev: RÖHM', 'trigger_column_count' => '1'],
			['id' => '61', 'purpose' => 'autosimple', 'name' => 'ONLY Karnasch', 'desc' => 'AutoGenerate only dev: Karnasch', 'trigger_column_count' => '1'],
			['id' => '62', 'purpose' => 'autosimple', 'name' => 'ONLY RHTC', 'desc' => 'AutoGenerate only dev: RHTC', 'trigger_column_count' => '1'],
			['id' => '63', 'purpose' => 'autosimple', 'name' => 'ONLY SOLA', 'desc' => 'AutoGenerate only dev: SOLA', 'trigger_column_count' => '1'],
			['id' => '64', 'purpose' => 'autosimple', 'name' => 'ONLY Virutex', 'desc' => 'AutoGenerate only dev: Virutex', 'trigger_column_count' => '1'],
			['id' => '65', 'purpose' => 'autosimple', 'name' => 'ONLY Steinel', 'desc' => 'AutoGenerate only dev: Steinel', 'trigger_column_count' => '1'],
			['id' => '66', 'purpose' => 'autosimple', 'name' => 'ONLY Magg', 'desc' => 'AutoGenerate only dev: Magg', 'trigger_column_count' => '1'],
			['id' => '67', 'purpose' => 'autosimple', 'name' => 'ONLY Evolution', 'desc' => 'AutoGenerate only dev: Evolution', 'trigger_column_count' => '1'],
			['id' => '68', 'purpose' => 'autosimple', 'name' => 'ONLY VeGA', 'desc' => 'AutoGenerate only dev: VeGA', 'trigger_column_count' => '1'],
			['id' => '69', 'purpose' => 'autosimple', 'name' => 'ONLY Claber', 'desc' => 'AutoGenerate only dev: Claber', 'trigger_column_count' => '1'],
			['id' => '70', 'purpose' => 'autosimple', 'name' => 'ONLY ALVE', 'desc' => 'AutoGenerate only dev: ALVE', 'trigger_column_count' => '1'],
			['id' => '71', 'purpose' => 'autosimple', 'name' => 'ONLY Weibang', 'desc' => 'AutoGenerate only dev: Weibang', 'trigger_column_count' => '1'],
			['id' => '72', 'purpose' => 'autosimple', 'name' => 'ONLY Tona', 'desc' => 'AutoGenerate only dev: Tona', 'trigger_column_count' => '1'],
			['id' => '73', 'purpose' => 'autosimple', 'name' => 'ONLY Dirotec', 'desc' => 'AutoGenerate only dev: Dirotec', 'trigger_column_count' => '1'],
			['id' => '74', 'purpose' => 'autosimple', 'name' => 'ONLY Narex Bučovice', 'desc' => 'AutoGenerate only dev: Narex Bučovice', 'trigger_column_count' => '1'],
			['id' => '75', 'purpose' => 'autosimple', 'name' => 'ONLY Nuair', 'desc' => 'AutoGenerate only dev: Nuair', 'trigger_column_count' => '1'],
			['id' => '76', 'purpose' => 'autosimple', 'name' => 'ONLY MS Nářadí', 'desc' => 'AutoGenerate only dev: MS Nářadí', 'trigger_column_count' => '1'],
			['id' => '77', 'purpose' => 'autosimple', 'name' => 'ONLY Paslode', 'desc' => 'AutoGenerate only dev: Paslode', 'trigger_column_count' => '1'],
			['id' => '78', 'purpose' => 'autosimple', 'name' => 'ONLY Walmec', 'desc' => 'AutoGenerate only dev: Walmec', 'trigger_column_count' => '1'],
			['id' => '79', 'purpose' => 'autosimple', 'name' => 'ONLY Wagner', 'desc' => 'AutoGenerate only dev: Wagner', 'trigger_column_count' => '1'],
			['id' => '80', 'purpose' => 'autosimple', 'name' => 'ONLY York', 'desc' => 'AutoGenerate only dev: York', 'trigger_column_count' => '1'],
			['id' => '81', 'purpose' => 'autosimple', 'name' => 'ONLY Kasper', 'desc' => 'AutoGenerate only dev: Kasper', 'trigger_column_count' => '1'],
			['id' => '82', 'purpose' => 'autosimple', 'name' => 'ONLY Reich by Holzher', 'desc' => 'AutoGenerate only dev: Reich by Holzher', 'trigger_column_count' => '1'],
			['id' => '83', 'purpose' => 'autosimple', 'name' => 'ONLY Gola nářadí', 'desc' => 'AutoGenerate only dev: Gola nářadí', 'trigger_column_count' => '1'],
			['id' => '84', 'purpose' => 'autosimple', 'name' => 'ONLY Banner', 'desc' => 'AutoGenerate only dev: Banner', 'trigger_column_count' => '1'],
			['id' => '85', 'purpose' => 'autosimple', 'name' => 'ONLY Konrád Karel', 'desc' => 'AutoGenerate only dev: Konrád Karel', 'trigger_column_count' => '1'],
			['id' => '86', 'purpose' => 'autosimple', 'name' => 'ONLY Proxxon', 'desc' => 'AutoGenerate only dev: Proxxon', 'trigger_column_count' => '1'],
			['id' => '87', 'purpose' => 'autosimple', 'name' => 'ONLY Stabila', 'desc' => 'AutoGenerate only dev: Stabila', 'trigger_column_count' => '1'],
			['id' => '88', 'purpose' => 'autosimple', 'name' => 'ONLY Ajax Jihlava', 'desc' => 'AutoGenerate only dev: Ajax Jihlava', 'trigger_column_count' => '1'],
			['id' => '89', 'purpose' => 'autosimple', 'name' => 'ONLY Hecht', 'desc' => 'AutoGenerate only dev: Hecht', 'trigger_column_count' => '1'],
			['id' => '90', 'purpose' => 'autosimple', 'name' => 'ONLY BeA', 'desc' => 'AutoGenerate only dev: BeA', 'trigger_column_count' => '1'],
			['id' => '91', 'purpose' => 'autosimple', 'name' => 'ONLY RUBI', 'desc' => 'AutoGenerate only dev: RUBI', 'trigger_column_count' => '1'],
			['id' => '92', 'purpose' => 'autosimple', 'name' => 'ONLY OPP Polička', 'desc' => 'AutoGenerate only dev: OPP Polička', 'trigger_column_count' => '1'],
			['id' => '93', 'purpose' => 'autosimple', 'name' => 'ONLY Normex', 'desc' => 'AutoGenerate only dev: Normex', 'trigger_column_count' => '1'],
			['id' => '94', 'purpose' => 'autosimple', 'name' => 'ONLY DiMartino', 'desc' => 'AutoGenerate only dev: DiMartino', 'trigger_column_count' => '1'],
			['id' => '95', 'purpose' => 'autosimple', 'name' => 'ONLY Rivet Factory', 'desc' => 'AutoGenerate only dev: Rivet Factory', 'trigger_column_count' => '1'],
			['id' => '96', 'purpose' => 'autosimple', 'name' => 'ONLY Prebena', 'desc' => 'AutoGenerate only dev: Prebena', 'trigger_column_count' => '1'],
			['id' => '97', 'purpose' => 'autosimple', 'name' => 'ONLY Mars Svratka', 'desc' => 'AutoGenerate only dev: Mars Svratka', 'trigger_column_count' => '1'],
			['id' => '98', 'purpose' => 'autosimple', 'name' => 'ONLY Pleschinger', 'desc' => 'AutoGenerate only dev: Pleschinger', 'trigger_column_count' => '1'],
			['id' => '99', 'purpose' => 'autosimple', 'name' => 'ONLY DenBraven', 'desc' => 'AutoGenerate only dev: DenBraven', 'trigger_column_count' => '1'],
			['id' => '100', 'purpose' => 'autosimple', 'name' => 'ONLY Fischer', 'desc' => 'AutoGenerate only dev: Fischer', 'trigger_column_count' => '1'],
			['id' => '101', 'purpose' => 'autosimple', 'name' => 'ONLY Omicron', 'desc' => 'AutoGenerate only dev: Omicron', 'trigger_column_count' => '1'],
			['id' => '102', 'purpose' => 'autosimple', 'name' => 'ONLY Elektrode Jesenice', 'desc' => 'AutoGenerate only dev: Elektrode Jesenice', 'trigger_column_count' => '1'],
			['id' => '103', 'purpose' => 'autosimple', 'name' => 'ONLY ESAB', 'desc' => 'AutoGenerate only dev: ESAB', 'trigger_column_count' => '1'],
			['id' => '104', 'purpose' => 'autosimple', 'name' => 'ONLY GeoFennel', 'desc' => 'AutoGenerate only dev: GeoFennel', 'trigger_column_count' => '1'],
			['id' => '105', 'purpose' => 'autosimple', 'name' => 'ONLY Montolit', 'desc' => 'AutoGenerate only dev: Montolit', 'trigger_column_count' => '1'],
			['id' => '106', 'purpose' => 'autosimple', 'name' => 'ONLY Clipper', 'desc' => 'AutoGenerate only dev: Clipper', 'trigger_column_count' => '1'],
			['id' => '107', 'purpose' => 'autosimple', 'name' => 'ONLY Rothenberger', 'desc' => 'AutoGenerate only dev: Rothenberger', 'trigger_column_count' => '1'],
			['id' => '108', 'purpose' => 'autosimple', 'name' => 'ONLY Cromwell', 'desc' => 'AutoGenerate only dev: Cromwell', 'trigger_column_count' => '1'],
			['id' => '109', 'purpose' => 'autosimple', 'name' => 'ONLY GreenLine', 'desc' => 'AutoGenerate only dev: GreenLine', 'trigger_column_count' => '1'],
			['id' => '110', 'purpose' => 'autosimple', 'name' => 'ONLY Kinex', 'desc' => 'AutoGenerate only dev: Kinex', 'trigger_column_count' => '1'],
			['id' => '111', 'purpose' => 'autosimple', 'name' => 'ONLY WD', 'desc' => 'AutoGenerate only dev: WD', 'trigger_column_count' => '1'],
			['id' => '112', 'purpose' => 'autosimple', 'name' => 'ONLY AgriFab', 'desc' => 'AutoGenerate only dev: AgriFab', 'trigger_column_count' => '1'],
			['id' => '113', 'purpose' => 'autosimple', 'name' => 'ONLY Arnold', 'desc' => 'AutoGenerate only dev: Arnold', 'trigger_column_count' => '1'],
			['id' => '114', 'purpose' => 'autosimple', 'name' => 'ONLY Biocin', 'desc' => 'AutoGenerate only dev: Biocin', 'trigger_column_count' => '1'],
			['id' => '115', 'purpose' => 'autosimple', 'name' => 'ONLY Britech', 'desc' => 'AutoGenerate only dev: Britech', 'trigger_column_count' => '1'],
			['id' => '116', 'purpose' => 'autosimple', 'name' => 'ONLY Cub Cadet', 'desc' => 'AutoGenerate only dev: Cub Cadet', 'trigger_column_count' => '1'],
			['id' => '117', 'purpose' => 'autosimple', 'name' => 'ONLY DWT', 'desc' => 'AutoGenerate only dev: DWT', 'trigger_column_count' => '1'],
			['id' => '118', 'purpose' => 'autosimple', 'name' => 'ONLY Elpumps', 'desc' => 'AutoGenerate only dev: Elpumps', 'trigger_column_count' => '1'],
			['id' => '119', 'purpose' => 'autosimple', 'name' => 'ONLY GTM', 'desc' => 'AutoGenerate only dev: GTM', 'trigger_column_count' => '1'],
			['id' => '120', 'purpose' => 'autosimple', 'name' => 'ONLY Greenworks', 'desc' => 'AutoGenerate only dev: Greenworks', 'trigger_column_count' => '1'],
			['id' => '121', 'purpose' => 'autosimple', 'name' => 'ONLY Homelite', 'desc' => 'AutoGenerate only dev: Homelite', 'trigger_column_count' => '1'],
			['id' => '122', 'purpose' => 'autosimple', 'name' => 'ONLY Kity', 'desc' => 'AutoGenerate only dev: Kity', 'trigger_column_count' => '1'],
			['id' => '123', 'purpose' => 'autosimple', 'name' => 'ONLY Marunaka', 'desc' => 'AutoGenerate only dev: Marunaka', 'trigger_column_count' => '1'],
			['id' => '124', 'purpose' => 'autosimple', 'name' => 'ONLY Michelin', 'desc' => 'AutoGenerate only dev: Michelin', 'trigger_column_count' => '1'],
			['id' => '125', 'purpose' => 'autosimple', 'name' => 'ONLY MTD', 'desc' => 'AutoGenerate only dev: MTD', 'trigger_column_count' => '1'],
			['id' => '126', 'purpose' => 'autosimple', 'name' => 'ONLY Palram', 'desc' => 'AutoGenerate only dev: Palram', 'trigger_column_count' => '1'],
			['id' => '127', 'purpose' => 'autosimple', 'name' => 'ONLY RYOBI', 'desc' => 'AutoGenerate only dev: RYOBI', 'trigger_column_count' => '1'],
			['id' => '128', 'purpose' => 'autosimple', 'name' => 'ONLY Riwall', 'desc' => 'AutoGenerate only dev: Riwall', 'trigger_column_count' => '1'],
			['id' => '129', 'purpose' => 'autosimple', 'name' => 'ONLY Sandri Garden', 'desc' => 'AutoGenerate only dev: Sandri Garden', 'trigger_column_count' => '1'],
			['id' => '130', 'purpose' => 'autosimple', 'name' => 'ONLY Scheppach', 'desc' => 'AutoGenerate only dev: Scheppach', 'trigger_column_count' => '1'],
			['id' => '131', 'purpose' => 'autosimple', 'name' => 'ONLY TurfMaster', 'desc' => 'AutoGenerate only dev: TurfMaster', 'trigger_column_count' => '1'],
			['id' => '132', 'purpose' => 'autosimple', 'name' => 'ONLY Woodster', 'desc' => 'AutoGenerate only dev: Woodster', 'trigger_column_count' => '1'],
			['id' => '133', 'purpose' => 'autosimple', 'name' => 'ONLY REMS', 'desc' => 'AutoGenerate only dev: REMS', 'trigger_column_count' => '1'],
			['id' => '134', 'purpose' => 'autosimple', 'name' => 'ONLY Triton', 'desc' => 'AutoGenerate only dev: Triton', 'trigger_column_count' => '1'],
			['id' => '135', 'purpose' => 'autosimple', 'name' => 'ONLY VM', 'desc' => 'AutoGenerate only dev: VM', 'trigger_column_count' => '1'],
			['id' => '136', 'purpose' => 'autosimple', 'name' => 'ONLY HealthLand', 'desc' => 'AutoGenerate only dev: HealthLand', 'trigger_column_count' => '1'],
			['id' => '137', 'purpose' => 'autosimple', 'name' => 'ONLY No Name', 'desc' => 'AutoGenerate only dev: No Name', 'trigger_column_count' => '1'],
			['id' => '138', 'purpose' => 'autosimple', 'name' => 'ONLY Sigma pumpy Hranice', 'desc' => 'AutoGenerate only dev: Sigma pumpy Hranice', 'trigger_column_count' => '1'],
			['id' => '139', 'purpose' => 'autosimple', 'name' => 'ONLY IGM', 'desc' => 'AutoGenerate only dev: IGM', 'trigger_column_count' => '1'],
			['id' => '140', 'purpose' => 'autosimple', 'name' => 'ONLY CMT', 'desc' => 'AutoGenerate only dev: CMT', 'trigger_column_count' => '1'],
			['id' => '141', 'purpose' => 'autosimple', 'name' => 'ONLY Fachmann', 'desc' => 'AutoGenerate only dev: Fachmann', 'trigger_column_count' => '1'],
			['id' => '142', 'purpose' => 'autosimple', 'name' => 'ONLY JET', 'desc' => 'AutoGenerate only dev: JET', 'trigger_column_count' => '1'],
			['id' => '143', 'purpose' => 'autosimple', 'name' => 'ONLY Silky', 'desc' => 'AutoGenerate only dev: Silky', 'trigger_column_count' => '1'],
			['id' => '144', 'purpose' => 'autosimple', 'name' => 'ONLY Titebond', 'desc' => 'AutoGenerate only dev: Titebond', 'trigger_column_count' => '1'],
			['id' => '145', 'purpose' => 'autosimple', 'name' => 'ONLY Uvex', 'desc' => 'AutoGenerate only dev: Uvex', 'trigger_column_count' => '1'],
			['id' => '146', 'purpose' => 'autosimple', 'name' => 'ONLY Extol', 'desc' => 'AutoGenerate only dev: Extol', 'trigger_column_count' => '1'],
			['id' => '147', 'purpose' => 'autosimple', 'name' => 'ONLY Heron', 'desc' => 'AutoGenerate only dev: Heron', 'trigger_column_count' => '1'],
			['id' => '148', 'purpose' => 'autosimple', 'name' => 'ONLY Balletto', 'desc' => 'AutoGenerate only dev: Balletto', 'trigger_column_count' => '1'],
			['id' => '149', 'purpose' => 'autosimple', 'name' => 'ONLY Fortum', 'desc' => 'AutoGenerate only dev: Fortum', 'trigger_column_count' => '1'],
			['id' => '150', 'purpose' => 'autosimple', 'name' => 'ONLY Freshhh', 'desc' => 'AutoGenerate only dev: Freshhh', 'trigger_column_count' => '1'],
			['id' => '151', 'purpose' => 'autosimple', 'name' => 'ONLY Imperia', 'desc' => 'AutoGenerate only dev: Imperia', 'trigger_column_count' => '1'],
			['id' => '152', 'purpose' => 'autosimple', 'name' => 'ONLY Kito', 'desc' => 'AutoGenerate only dev: Kito', 'trigger_column_count' => '1'],
			['id' => '153', 'purpose' => 'autosimple', 'name' => 'ONLY Opera', 'desc' => 'AutoGenerate only dev: Opera', 'trigger_column_count' => '1'],
			['id' => '154', 'purpose' => 'autosimple', 'name' => 'ONLY Sonata', 'desc' => 'AutoGenerate only dev: Sonata', 'trigger_column_count' => '1'],
			['id' => '155', 'purpose' => 'autosimple', 'name' => 'ONLY Viking', 'desc' => 'AutoGenerate only dev: Viking', 'trigger_column_count' => '1'],
			['id' => '156', 'purpose' => 'autosimple', 'name' => 'ONLY Vittoria', 'desc' => 'AutoGenerate only dev: Vittoria', 'trigger_column_count' => '1']
		];

		foreach ($mixture_dev as $row) {
			DB::table('mixture_dev')->insert([
				'id'      => $row['id'],
				'purpose' => $row['purpose'],
				'name'    => $row['name'],
				'desc'    => $row['desc']
			]);
		}
	}
}